version: '3'


volumes:
  local_volume: {}

services:
  echo:
    build:
      context: .
      dockerfile: ./echo/Dockerfile
    image: echo_image
    volumes:
      - local_volume:/app

  cat:
    build:
      context: .
      dockerfile: ./cat/Dockerfile
    image: cat_image
    depends_on:
      - echo
    volumes:
      - local_volume:/app
